# Generated by Django 6.0.6 on 2026-06-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H3Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=50, unique=True)),
                ('order_index', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', '待标注'), ('annotated', '已标注'), ('skipped', '已跳过')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('geo_polygon', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotator.h3cell')),
            ],
            options={
                'unique_together': {('cell', 'year')},
            },
        ),
    ]
