# Generated by Django 6.0.6 on 2026-06-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_h3cell_note_h3cell_result'),
    ]

    operations = [
        # 先加 email 字段
        migrations.AddField(
            model_name='annotation',
            name='email',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        # email 存在后再改 unique_together
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('cell', 'email', 'year')},
        ),
        migrations.RemoveField(
            model_name='h3cell',
            name='note',
        ),
        migrations.RemoveField(
            model_name='h3cell',
            name='result',
        ),
        migrations.RemoveField(
            model_name='h3cell',
            name='status',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='geo_polygon',
        ),
        migrations.CreateModel(
            name='CellResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('result', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='annotator.h3cell')),
            ],
            options={
                'unique_together': {('cell', 'email')},
            },
        ),
    ]
